site_name: Fish Feeder Documentation
repo_url: https://github.com/ColoMAX/fish_feeder
site_url: https://ColoMAX.github.io/fish_feeder

nav:
  - index.md
  - "getting-started.md"
  - "overview.md"

theme:
  name: readthedocs
  font:
    text: Roboto
    code: Ubuntu Mono # Roboto mono