substitutions:
  # Here you can modify basic configs
  VIB_MOTOR_GPIO:         GPIO14 # see pin-"number" https://esphome.io/guides/configuration-types#config-pin-schema
  SCREW_MOTOR_PWM_GPIO:   GPIO4
  LID_MOTOR_PWM_GPIO:     GPIO14
  LIGHT_RELAY_GPIO:       GPIO13
  BUTTON_GPIO:            GPIO5
  CHIPSET:                esp8266 # or esp32, rp2040 or others, see platforms https://esphome.io/index.html#platforms
  BOARD:                  d1_mini # or e.g. esp32doit-devkit-v1
  NAME_POSTFIX:           "" # must be a string
  # ALSO CHANGE THE ff_hal_ file! to the same name as CHIPSET
  LOGS_IN_WEB:            "false" # Disable the visibility of the logs on web interface

packages:
  ff_common: !include common.yaml
  ff_hal: !include ff_hal_esp8266.yaml # ALSO CHANGE THIS!!

${CHIPSET}:
  board: ${BOARD}

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
#api:

ota:
  password: !secret ota_psk

### Add you additional customizations here
light:
  - platform: binary
    name: 00. Fish tank light
    output: light_relay
output:
  - id: light_relay
    platform: gpio
    pin: ${LIGHT_RELAY_GPIO}

switch:
  - platform: gpio
    pin: ${VIB_MOTOR_GPIO}             # Vibration motor GPIO
    name: vibration motor
    internal: true
    id: vib_motor
    on_turn_on:
      - delay: 100ms
      - switch.turn_off: vib_motor
